version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./logs:/var/log
      - .:/app
    command: /start.sh
